version: '3.2'
services:
    zoo1:
        image: zookeeper
        restart: always
        volumes:
            - ./zoo1/data:/data
            - ./zoo1/datalog:/datalog
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        volumes:
            - ./zoo2/data:/data
            - ./zoo2/datalog:/datalog
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
